# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='match_only',
            field=models.DecimalField(blank=True, decimal_places=12, default=0, max_digits=19, null=True),
        ),
    ]
